export const leatherBags = [
  {
    id: 1,
    name: "Classic Leather Tote",
    description: "A timeless and elegant tote made from premium leather.",
    price: 149.99,
    imageUrl: "./src/assets/images/collection-image-1.png",
  },
  {
    id: 2,
    name: "Vintage Leather Bag",
    description: "A stylish and classic messenger bag with a vintage look.",
    price: 199.99,
    imageUrl: "./src/assets/images/collection-image-2.png",
  },
  {
    id: 3,
    name: "Leather Backpack",
    description: "A durable and versatile leather backpack for everyday use.",
    price: 179.99,
    imageUrl: "./src/assets/images/collection-image-3.png",
  },
  {
    id: 4,
    name: "Leather Crossbody Bag",
    description: "A compact and convenient crossbody bag for versatility.",
    price: 129.99,
    imageUrl: "./src/assets/images/collection-image-4.png",
  },
  {
    id: 5,
    name: "Leather Duffel Bag",
    description: "A spacious and sturdy duffel bag for weekend trips.",
    price: 249.99,
    imageUrl: "./src/assets/images/collection-image-5.png",
  },
  {
    id: 6,
    name: "Leather Satchel",
    description: "A versatile and practical satchel with multiple compartments.",
    price: 159.99,
    imageUrl: "./src/assets/images/collection-image-6.png",
  },
  {
    id: 7,
    name: "Leather Handbag",
    description: "A chic and stylish handbag for women, perfect for any occasion.",
    price: 219.99,
    imageUrl: "./src/assets/images/collection-image-7.png",
  },
  {
    id: 8,
    name: "Leather Shoulder Bag",
    description: "A stylish, vintage and classic shoulder bag with a classic design.",
    price: 139.99,
    imageUrl: "./src/assets/images/collection-image-8.png",
  },
  {
    id: 9,
    name: "Leather Briefcase",
    description: "A professional and durable leather briefcase for business.",
    price: 229.99,
    imageUrl: "./src/assets/images/collection-image-9.png",
  },
  {
    id: 10,
    name: "Leather Saddle Bag",
    description: "A chic and trendy leather saddle bag for casual outings.",
    price: 119.99,
    imageUrl: "./src/assets/images/collection-image-10.png",
  },
  {
    id: 11,
    name: "Leather Hobo Bag",
    description: "A spacious and comfortable hobo bag made from soft leather.",
    price: 149.99,
    imageUrl: "./src/assets/images/collection-image-11.png",
  },
  {
    id: 12,
    name: "Leather Belt Bag",
    description: "A convenient and handy belt bag for carrying essentials.",
    price: 99.99,
    imageUrl: "./src/assets/images/collection-image-12.png",
  },
  {
    id: 13,
    name: "Leather Bucket Bag",
    description: "A trendy and stylish bucket bag with a drawstring closure.",
    price: 129.99,
    imageUrl: "./src/assets/images/collection-image-13.png",
  },
  {
    id: 14,
    name: "Leather Clutch",
    description: "A sleek and elegant leather clutch for evening events.",
    price: 89.99,
    imageUrl: "./src/assets/images/collection-image-14.png",
  },
  {
    id: 15,
    name: "Leather Weekender Bag",
    description: "A large and versatile weekender bag for travel and fun.",
    price: 279.99,
    imageUrl: "./src/assets/images/collection-image-15.png",
  },
  {
    id: 16,
    name: "Leather Fanny Pack",
    description: "A stylish and convenient fanny pack for on-the-go convenience.",
    price: 79.99,
    imageUrl: "./src/assets/images/collection-image-16.png",
  },
];
